### ISSUE TITLE
if code is released , pls remind me 

### ISSUE THREAD

**Issue by danboardxu** [ArchipLab-LinfengZhang/pytorch-self-distillation#5]

**Comment by luanyunteng** [comment]
I have implemented an version of this method in pytorch, and you may refer to it. [https://github.com/luanyunteng/pytorch-be-your-own-teacher.git](url)

**Comment by danboardxu** [comment]
thx




| |
徐毅
邮箱：15151935675@163.com
|

签名由 网易邮箱大师 定制

On 02/26/2020 09:55, shinian wrote:

I have implemented an version of this method in pytorch, and you may refer to it. https://github.com/luanyunteng/pytorch-be-your-own-teacher.git

**Comment by ArchipLab-LinfengZhang** [comment]
Please refer to https://github.com/ArchipLab-LinfengZhang/pytorch-self-distillation-final
