### ISSUE TITLE
would the code release in these few months?

### ISSUE THREAD

**Issue by benj6an9** [ArchipLab-LinfengZhang/pytorch-self-distillation#6]

**Comment by luanyunteng** [comment]
I have implemented an version of this method in pytorch, and you may refer to it. [https://github.com/luanyunteng/pytorch-be-your-own-teacher.git](url)

**Comment by ArchipLab-LinfengZhang** [comment]
Please refer to https://github.com/ArchipLab-LinfengZhang/pytorch-self-distillation-final
